[settings]
experimental = true
unix_default_inline_shell_args = "zsh -c"
# unix_default_inline_shell_args = "zsh"
status.show_prepare_stale = false
pipx.uvx = true

[tools]
# python = { version = ">=3.8", postinstall = "mise sync python --uv" }
uv = { version = "latest", postinstall = { task = "init" } }
ruff = "latest"

[settings.python]
uv_venv_auto = "create|source"
uv_venv_create_args = [
    "--verbose",
    "--seed",
    "--python-preference=only-managed",
    #"--quiet",
    "--allow-existing",
    "--python='>=3.8,<3.10'"
]


#[prepare.uv]
#description = """
#https://mise.jdx.dev/dev-tools/prepare.html#built-in-providers
#https://mise.jdx.dev/configuration.html#idiomatic-version-files
#"""
#auto = false
#sources = ["pyproject.toml", "uv.lock"]
#outputs = [".venv/", "uv.lock"]
#run = "uv lock && uv sync"
#

[hooks]
enter = [
    { task = "uv-ensure-venv" },
    { script = "source .venv/bin/activate", shell = "zsh" },
    { script = "which python", shell = "zsh -c" }
]
leave = { script = "[[ -n \"$VIRTUAL_ENV\" ]] && deactivate", shell = "zsh" }

[tasks.uv-ensure-venv]
# silent = true
# tools.uv = "latest"
# raw = true
dir = "{{config_root}}"
shell = "mise exec -- zsh -c"
run = "uv venv --verbose --allow-existing --python=\">=3.8,<3.10\""

[tasks.uv-source-venv]
dir = "{{config_root}}"
shell = "mise exec -- zsh -c"
#raw = true
run = "source .venv/bin/activate"

[tasks.install-dependencies]
shell = "mise exec -- zsh -c"
run = "uv lock && uv sync"

[env]
# _.python.venv = { path = ".venv", create = false }
PYTHONPATH = "{{config_root}}"
INSTALL_TRAINING_DEPS = "1"
OLLAMA_HOST = "127.0.0.1"
OLLAMA_PORT = "11434"
MODEL_COMPLETION_DAEMON_PORT = "11435"
# MISE_VERBOSE = true




[tasks.start-model-completion-daemon]
run = '''

'''



[tasks.install-the-old-way]
run = '''
sh ./install.sh
'''